# Generated by Django 5.1.2 on 2024-10-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image1_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product'),
            preserve_default=False,
        ),
    ]
