# Generated by Django 5.1.2 on 2024-10-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_has_discount_productcolor_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
