# Generated by Django 5.1.2 on 2024-10-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_product_colors_product_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
    ]
