# Generated by Django 5.1.2 on 2024-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_product_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_colors',
            field=models.ManyToManyField(blank=True, related_name='related_products', to='products.productcolor'),
        ),
    ]
