# Generated by Django 5.1.2 on 2024-10-29 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
    ]
