# Generated by Django 5.1.2 on 2024-10-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_product_colors_product_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_colors',
            field=models.ManyToManyField(related_name='products', to='products.productcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(related_name='products', to='products.productimage'),
        ),
    ]
