# Generated by Django 5.1.2 on 2024-10-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_product_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.productcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='products.productimage'),
        ),
    ]
