# Generated by Django 5.1.2 on 2024-10-30 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_product_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
    ]
